import {
  Bike,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  Coffee,
  CreditCard,
  Dumbbell,
  Film,
  Fish,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HeartPulse,
  Home,
  Key,
  Library,
  Lightbulb,
  MoreHorizontal,
  Music,
  PartyPopper,
  PawPrint,
  Pill,
  Pizza,
  Plane,
  Shirt,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Star,
  Stethoscope,
  Train,
  TreePine,
  TrendingUp,
  Utensils,
  Wallet,
  Watch,
  Wifi,
  Wrench,
} from 'lucide-react';

export const iconCategoryFromBackendMap = {
  ShoppingCart: <ShoppingCart />,
  Utensils: <Utensils />,
  Coffee: <Coffee />,
  Pizza: <Pizza />,

  Bus: <Bus />,
  Train: <Train />,
  Car: <Car />,
  Plane: <Plane />,

  Home: <Home />,
  Building2: <Building2 />,
  Key: <Key />,

  HeartPulse: <HeartPulse />,
  Stethoscope: <Stethoscope />,
  Pill: <Pill />,

  GraduationCap: <GraduationCap />,
  BookOpen: <BookOpen />,
  Library: <Library />,

  Gamepad2: <Gamepad2 />,
  Film: <Film />,
  Music: <Music />,

  Shirt: <Shirt />,
  Watch: <Watch />,

  Smartphone: <Smartphone />,
  Wifi: <Wifi />,
  Globe: <Globe />,

  Gift: <Gift />,
  PartyPopper: <PartyPopper />,

  Wallet: <Wallet />,
  CreditCard: <CreditCard />,
  Briefcase: <Briefcase />,
  TrendingUp: <TrendingUp />,

  Dumbbell: <Dumbbell />,
  Bike: <Bike />,

  PawPrint: <PawPrint />,
  Fish: <Fish />,

  TreePine: <TreePine />,

  Wrench: <Wrench />,
  Hammer: <Hammer />,

  Lightbulb: <Lightbulb />,
  Sparkles: <Sparkles />,
  Star: <Star />,

  MoreHorizontal: <MoreHorizontal />,
};

export type IconCategory = keyof typeof iconCategoryFromBackendMap;

export const iconsKeys: readonly (keyof typeof iconCategoryFromBackendMap)[] = [
  'ShoppingCart',
  'Utensils',
  'Coffee',
  'Pizza',
  'Bus',
  'Train',
  'Car',
  'Plane',
  'Home',
  'Building2',
  'Key',
  'HeartPulse',
  'Stethoscope',
  'Pill',
  'GraduationCap',
  'BookOpen',
  'Library',
  'Gamepad2',
  'Film',
  'Music',
  'Shirt',
  'Watch',
  'Smartphone',
  'Wifi',
  'Globe',
  'Gift',
  'PartyPopper',
  'Wallet',
  'CreditCard',
  'Briefcase',
  'TrendingUp',
  'Dumbbell',
  'Bike',
  'PawPrint',
  'Fish',
  'TreePine',
  'Wrench',
  'Hammer',
  'Lightbulb',
  'Sparkles',
  'Star',
  'MoreHorizontal',
] as const;
